server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
  port: 9090

spring:
  datasource:
    primary:
      hikari: # 초당 30tps 트랜잭션 설정
        driver-class-name: org.mariadb.jdbc.Driver
        pool-name: SpringBootJPAHikariCP
        minimum-idle: 5
        maximum-pool-size: 20
        idle-timeout: 30000
        max-lifetime: 2000000
        connection-timeout: 30000
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: none
    properties:
      hibernate:
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

## p6spy
decorator:
  datasource:
    p6spy:
      enable-logging: false